Exception on /gm/gmtools/upload_cdn_file [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/route.py", line 437, in gm_tools_upload_cdn_config
    extra = demjson.decode(request.form['0'],encoding='utf-8')
  File "/usr/local/lib/python2.7/site-packages/demjson.py", line 5701, in decode
    return_stats=(return_stats or write_stats) )
  File "/usr/local/lib/python2.7/site-packages/demjson.py", line 4917, in decode
    raise errors[0]
JSONDecodeError: ('Unknown identifier', u'object')
